# Generated by Django 3.1.3 on 2022-02-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_number', models.CharField(max_length=20)),
                ('live_product', models.BooleanField(default=True)),
                ('car_id', models.CharField(default='74483492771847797120203436161993747589', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ColdHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.FloatField(default=1643697789.376668)),
                ('exit_date', models.FloatField(null=True)),
                ('pallet_status', models.BooleanField(default=True)),
                ('total_pallet_weight', models.FloatField()),
                ('pallet_weight_without_product', models.FloatField(null=True)),
                ('number_of_box', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=15)),
                ('cold_house_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('company_id', models.CharField(default='74483492138022497006088735413642144901', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('driver_id', models.CharField(default='74483492851075959634467773755537697925', max_length=250, primary_key=True, serialize=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.car')),
            ],
        ),
        migrations.CreateModel(
            name='FirstWeightLifting',
            fields=[
                ('choise_status', models.BooleanField(default=False)),
                ('weighting_time', models.FloatField(default=1643697789.3726637)),
                ('weight', models.FloatField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('weight_lifting_id', models.CharField(default='74483493009532284662996448942625598597', max_length=250, primary_key=True, serialize=False)),
                ('sales_category', models.CharField(choices=[('P', 'pre-cold'), ('D', 'distribute'), ('F', 'freezing tunnel')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('product_owner_id', models.CharField(default='74483492692619634605939098568449797253', max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLiftingManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Weight_Lifting_Manager_id', models.CharField(default='74483492375706984548881748194273995909', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('sales_manager_id', models.CharField(default='74483492296478822034617410600730045573', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreColdManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Pre_Cold_id', models.CharField(default='74483492613391472091674760974905846917', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreCold',
            fields=[
                ('pc_id', models.CharField(default='74483493088760447177260786536169548933', max_length=250, primary_key=True, serialize=False)),
                ('entry_time', models.FloatField(default=1643697789.3737237)),
                ('exit_time', models.FloatField(null=True)),
                ('box_num', models.IntegerField(default=1)),
                ('weight', models.FloatField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('pre_cold_id', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=25, null=True)),
                ('product_pre_cold_status', models.BooleanField(default=True)),
                ('First_Weight_Lifting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.firstweightlifting')),
                ('PreCold_Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.precoldmanager')),
            ],
        ),
        migrations.CreateModel(
            name='PaperBox',
            fields=[
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('sub_product_category', models.CharField(choices=[('W', 'wing'), ('N', 'neck'), ('E', 'leg'), ('H', 'heart'), ('L', 'liver'), ('K', 'kidney'), ('S', 'sangdan'), ('B', 'body'), ('O', 'other')], default='B', max_length=1)),
                ('paper_box_weight', models.FloatField()),
                ('box_status', models.BooleanField(default=False)),
                ('box_cold_house_exp', models.BooleanField(default=False)),
                ('number_of_product', models.IntegerField()),
                ('packing_time', models.FloatField(default=1643697789.3778186)),
                ('expiration_time', models.IntegerField(default=30)),
                ('box_id', models.CharField(default='74483493326444934720053799316801399941', max_length=250, primary_key=True, serialize=False)),
                ('cold_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.coldhouse')),
            ],
        ),
        migrations.CreateModel(
            name='LiveWeighbridgeManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Live_Weighbridge_Manager_id', models.CharField(default='74483492534163309577410423381361896581', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveWeighbridge',
            fields=[
                ('live_weighbridge_id', models.CharField(default='74483492930304122148732111349081648261', max_length=250, primary_key=True, serialize=False)),
                ('final_weight', models.FloatField(null=True)),
                ('car_weight', models.FloatField(null=True)),
                ('car_empty', models.BooleanField(default=False)),
                ('weighting_date', models.FloatField(default=1643697789.3715847)),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('slaughter_status', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('avicultureـcity', models.CharField(default='-', max_length=25)),
                ('avicultureـname', models.CharField(default='-', max_length=25)),
                ('slaughter_start_date', models.FloatField(null=True)),
                ('slaughter_finish_date', models.FloatField(null=True)),
                ('buy_price', models.IntegerField()),
                ('Live_Weighbridge_Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.liveweighbridgemanager')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='FreezingTunnelManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Freezing_tunnel_Manager_id', models.CharField(default='74483492454935147063146085787817946245', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreezingTunnel',
            fields=[
                ('freeze_tunnel_id', models.CharField(default='74483493247216772205789461723257449605', max_length=250, primary_key=True, serialize=False)),
                ('entry_date', models.FloatField(default=1643697789.3757422)),
                ('exit_date', models.FloatField(null=True)),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('weight', models.FloatField()),
                ('box_num', models.IntegerField(default=1)),
                ('tunnel_id', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='آیا خارج شده یا نه')),
                ('first_weight_lifting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.firstweightlifting')),
                ('freezing_tunnel_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.freezingtunnelmanager')),
            ],
        ),
        migrations.AddField(
            model_name='firstweightlifting',
            name='Live_Weigh_Bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.liveweighbridge'),
        ),
        migrations.AddField(
            model_name='firstweightlifting',
            name='Weight_Lifting_Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.weightliftingmanager'),
        ),
        migrations.CreateModel(
            name='Distributed',
            fields=[
                ('date', models.FloatField(default=1643697789.3746986)),
                ('weight', models.FloatField()),
                ('sale_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('bill_of_lading', models.CharField(default='74483493167988609691525124129713499269', max_length=250, primary_key=True, serialize=False)),
                ('number_of_box', models.IntegerField(null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.driver')),
                ('first_weight_lifting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.firstweightlifting')),
                ('sales_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.salesmanager')),
            ],
        ),
        migrations.AddField(
            model_name='coldhouse',
            name='freezing_tunnel_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.freezingtunnelmanager'),
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('ceo_id', models.CharField(default='74483492217250659520353073007186095237', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='product_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.productowner'),
        ),
    ]
