# Generated by Django 3.1.3 on 2021-12-18 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_number', models.CharField(max_length=20)),
                ('live_product', models.BooleanField(default=True)),
                ('car_id', models.CharField(default='115923600463857475894786262692754751492', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ColdHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.FloatField(default=1639813473.261886)),
                ('exit_date', models.FloatField(null=True)),
                ('pallet_status', models.BooleanField(default=True)),
                ('total_pallet_weight', models.FloatField()),
                ('pallet_weight_whitout_product', models.FloatField(null=True)),
                ('number_of_box', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=15)),
                ('cold_house_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('company_id', models.CharField(default='115923599830032175780671561944403148804', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('driver_id', models.CharField(default='115923600543085638409050600286298701828', max_length=250, primary_key=True, serialize=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.car')),
            ],
        ),
        migrations.CreateModel(
            name='FirstWeightLifting',
            fields=[
                ('weighting_time', models.FloatField(default=1639813473.2575283)),
                ('weight', models.FloatField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('weight_lifting_id', models.CharField(default='115923600701541963437579275473386602500', max_length=250, primary_key=True, serialize=False)),
                ('sales_category', models.CharField(choices=[('P', 'pre-cold'), ('D', 'distribute'), ('F', 'freezing tunnel')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('product_owner_id', models.CharField(default='115923600384629313380521925099210801156', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLiftingManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Weight_Lifting_Manager_id', models.CharField(default='115923600067716663323464574725034999812', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('sales_manager_id', models.CharField(default='115923599988488500809200237131491049476', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreColdManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Pre_Cold_id', models.CharField(default='115923600305401150866257587505666850820', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreCold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.FloatField(default=1639813473.2584188)),
                ('exit_time', models.FloatField(null=True)),
                ('weight', models.FloatField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('pre_cold_id', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=25, null=True)),
                ('product_pre_cold_status', models.BooleanField(default=True)),
                ('First_Weight_Lifting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.firstweightlifting')),
                ('PreCold_Manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.precoldmanager')),
            ],
        ),
        migrations.CreateModel(
            name='PaperBox',
            fields=[
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('paper_box_weight', models.FloatField()),
                ('number_of_product', models.IntegerField()),
                ('packing_time', models.FloatField(default=1639813473.2628384)),
                ('box_id', models.CharField(default='115923600859998288466107950660474503172', max_length=250, primary_key=True, serialize=False)),
                ('cold_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.coldhouse')),
            ],
        ),
        migrations.CreateModel(
            name='LiveWeighbridgeManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Live_Weighbridge_Manager_id', models.CharField(default='115923600226172988351993249912122900484', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveWeighbridge',
            fields=[
                ('live_weighbridge_id', models.CharField(default='115923600622313800923314937879842652164', max_length=250, primary_key=True, serialize=False)),
                ('final_weight', models.FloatField()),
                ('car_weight', models.FloatField(null=True)),
                ('car_empty', models.BooleanField(default=False)),
                ('weighting_date', models.FloatField(default=1639813473.2564785)),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('slaughter_status', models.BooleanField(default=False)),
                ('slaughter_start_date', models.FloatField(null=True)),
                ('slaughter_finish_date', models.FloatField(null=True)),
                ('buy_price', models.IntegerField()),
                ('Live_Weighbridge_Manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.liveweighbridgemanager')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='FreezingTunnelManager',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('Freezing_tunnel_Manager_id', models.CharField(default='115923600146944825837728912318578950148', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreezingTunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.FloatField()),
                ('exit_date', models.FloatField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('weight', models.FloatField()),
                ('tunnel_id', models.IntegerField()),
                ('pallet_id', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='آیا خارج شده یا نه')),
                ('first_weight_lifting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.firstweightlifting')),
                ('freezing_tunnel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.freezingtunnelmanager')),
            ],
        ),
        migrations.AddField(
            model_name='firstweightlifting',
            name='Live_Weigh_Bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.liveweighbridge'),
        ),
        migrations.AddField(
            model_name='firstweightlifting',
            name='Weight_Lifting_Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.weightliftingmanager'),
        ),
        migrations.CreateModel(
            name='Distributed',
            fields=[
                ('date', models.FloatField(default=1639813473.25956)),
                ('weight', models.FloatField()),
                ('sale_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('C', 'chicken'), ('T', 'turkey'), ('Q', 'quail')], max_length=1)),
                ('bill_of_lading', models.CharField(default='115923600780770125951843613066930552836', max_length=250, primary_key=True, serialize=False)),
                ('number_of_box', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.driver')),
                ('first_weight_lifting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.firstweightlifting')),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.salesmanager')),
            ],
        ),
        migrations.AddField(
            model_name='coldhouse',
            name='freezing_tunnel_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.freezingtunnelmanager'),
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('ceo_id', models.CharField(default='115923599909260338294935899537947099140', max_length=250, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WareHouseApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='product_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.productowner'),
        ),
    ]
