# Generated by Django 3.1.3 on 2022-02-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviculture',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('aviculture_id', models.CharField(default='6693486612451437244378124114297032047', max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_numer1',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='car',
            name='car_numer2',
            field=models.CharField(default='ع', max_length=1),
        ),
        migrations.AddField(
            model_name='car',
            name='car_numer3',
            field=models.IntegerField(default=111),
        ),
        migrations.AddField(
            model_name='car',
            name='car_numer4',
            field=models.IntegerField(default=87),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='cage_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.car'),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='losses_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='losses_weight',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='lwb_category',
            field=models.CharField(choices=[('O', 'Order'), ('W', 'Weighting'), ('R', 'Reject')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='order_weight',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='product_num_in_cage',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='product_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.productowner'),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='victim_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='victim_weight',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default='6693486453995112215849448927209131375', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='ceo_id',
            field=models.CharField(default='6693485899397974615999085772401479023', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date',
            field=models.FloatField(default=1644220401.3315272),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='6693485820169812101734748178857528687', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='bill_of_lading',
            field=models.CharField(default='6693486929364087301435474488472833391', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date',
            field=models.FloatField(default=1644220401.3296406),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='6693486533223274730113786520753081711', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weight_lifting_id',
            field=models.CharField(default='6693486770907762272906799301384932719', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time',
            field=models.FloatField(default=1644220401.328001),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date',
            field=models.FloatField(default=1644220401.3305514),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='freeze_tunnel_id',
            field=models.CharField(default='6693487008592249815699812082016783727', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freezingtunnelmanager',
            name='Freezing_tunnel_Manager_id',
            field=models.CharField(default='6693486137082462158792098553033330031', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='buy_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.driver'),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='live_weighbridge_id',
            field=models.CharField(default='6693486691679599758642461707840982383', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date',
            field=models.FloatField(default=1644220401.3264906, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridgemanager',
            name='Live_Weighbridge_Manager_id',
            field=models.CharField(default='6693486216310624673056436146577280367', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='box_id',
            field=models.CharField(default='6693487087820412329964149675560734063', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time',
            field=models.FloatField(default=1644220401.332383),
        ),
        migrations.AlterField(
            model_name='precold',
            name='entry_time',
            field=models.FloatField(default=1644220401.3288088),
        ),
        migrations.AlterField(
            model_name='precold',
            name='pc_id',
            field=models.CharField(default='6693486850135924787171136894928883055', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precoldmanager',
            name='Pre_Cold_id',
            field=models.CharField(default='6693486295538787187320773740121230703', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='product_owner_id',
            field=models.CharField(default='6693486374766949701585111333665181039', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='sales_manager_id',
            field=models.CharField(default='6693485978626137130263423365945429359', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightliftingmanager',
            name='Weight_Lifting_Manager_id',
            field=models.CharField(default='6693486057854299644527760959489379695', max_length=250, primary_key=True, serialize=False),
        ),
    ]
