# Generated by Django 3.1.3 on 2022-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseApp', '0013_auto_20220307_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='account_side',
            field=models.CharField(default='شرکت', max_length=20),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='aviculture_avg_weight',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='fuel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='order_Manager',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='salughter_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='liveweighbridge',
            name='source_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='automation',
            name='code',
            field=models.CharField(default=7417, max_length=10),
        ),
        migrations.AlterField(
            model_name='aviculture',
            name='aviculture_id',
            field=models.CharField(default='63613644869597069211839953396956988878', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default='63613644711140744183311278209869088206', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='ceo_id',
            field=models.CharField(default='63613644077315444069196577461517485518', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='cold_house_primary_key',
            field=models.CharField(default='63613645582650531840218991738852541902', max_length=150),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date',
            field=models.FloatField(default=1646722291.627191),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='exit_date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='63613643998087281554932239867973535182', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='bill_of_lading',
            field=models.CharField(default='63613645265737881783161641364676740558', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date',
            field=models.FloatField(default=1646722291.6251109),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='sales_input_idistd',
            field=models.CharField(default='63613645344966044297425978958220690894', max_length=200),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='create_time',
            field=models.FloatField(default=1646722291.62428),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='create_time_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='dist_id',
            field=models.CharField(default='63613645186509719268897303771132790222', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time',
            field=models.FloatField(default=1646722291.6243246),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='63613644790368906697575615803413038542', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weight_lifting_id',
            field=models.CharField(default='63613645028053394240368628584044889550', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time',
            field=models.FloatField(default=1646722291.6224248),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date',
            field=models.FloatField(default=1646722291.6261516),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='exit_date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='freeze_tunnel_id',
            field=models.CharField(default='63613645424194206811690316551764641230', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='input_id',
            field=models.CharField(default='63613645503422369325954654145308591566', max_length=200),
        ),
        migrations.AlterField(
            model_name='freezingtunnelmanager',
            name='Freezing_tunnel_Manager_id',
            field=models.CharField(default='63613644314999931611989590242149336526', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='Live_Weighbridge_Manager',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='live_weighbridge_id',
            field=models.CharField(default='63613644948825231726104290990500939214', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date',
            field=models.FloatField(default=1646722291.6206243, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridgemanager',
            name='Live_Weighbridge_Manager_id',
            field=models.CharField(default='63613644394228094126253927835693286862', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='box_id',
            field=models.CharField(default='63613645661878694354483329332396492238', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='exit_time',
            field=models.FloatField(default=1646722291.62844, null=True),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time',
            field=models.FloatField(default=1646722291.6283927),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='precold',
            name='entry_time',
            field=models.FloatField(default=1646722291.623345),
        ),
        migrations.AlterField(
            model_name='precold',
            name='entry_time_format',
            field=models.CharField(default='Tue Mar  8 06:51:31 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='precold',
            name='pc_id',
            field=models.CharField(default='63613645107281556754632966177588839886', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precoldmanager',
            name='Pre_Cold_id',
            field=models.CharField(default='63613644473456256640518265429237237198', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='product_owner_id',
            field=models.CharField(default='63613644631912581669046940616325137870', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='sales_manager_id',
            field=models.CharField(default='63613644156543606583460915055061435854', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slaughteremployee',
            name='Slaughter_Employee_id',
            field=models.CharField(default='63613644552684419154782603022781187534', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightliftingmanager',
            name='Weight_Lifting_Manager_id',
            field=models.CharField(default='63613644235771769097725252648605386190', max_length=250, primary_key=True, serialize=False),
        ),
    ]
