# Generated by Django 4.0.3 on 2022-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseApp', '0021_remove_distributedroot_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedroot',
            name='out_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='code',
            field=models.CharField(default=2548, max_length=10),
        ),
        migrations.AlterField(
            model_name='aviculture',
            name='aviculture_id',
            field=models.CharField(default='144050480778893264932168015904798548591', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default='144048904138459231071849904380186862191', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='ceo_id',
            field=models.CharField(default='144045424437561604582142795929888105071', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='cold_house_primary_key',
            field=models.CharField(default='144054446940708729004907948714952368751', max_length=150),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date',
            field=models.FloatField(default=1647182384.140342),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='144044564811998324814079905978026959471', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='bill_of_lading',
            field=models.CharField(default='144053352799784407014405781872998228591', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date',
            field=models.FloatField(default=1647182384.138853),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='sales_input_idistd',
            field=models.CharField(default='144053407467216541856798721418323960431', max_length=200),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='dist_id',
            field=models.CharField(default='144052675398994910054319357072222855791', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time',
            field=models.FloatField(default=1647182384.1381361),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time',
            field=models.FloatField(default=1647182384.1381629),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time',
            field=models.FloatField(default=1647182384.138186),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='full_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time',
            field=models.FloatField(default=1647182384.1381037),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='144049282056794424112740225584829964911', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weight_lifting_id',
            field=models.CharField(default='144051710399975486314687467706907763311', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time',
            field=models.FloatField(default=1647182384.1367555),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date',
            field=models.FloatField(default=1647182384.1395333),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='freeze_tunnel_id',
            field=models.CharField(default='144053809154000489176990320686152163951', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='input_id',
            field=models.CharField(default='144054056345867533681723612543277212271', max_length=200),
        ),
        migrations.AlterField(
            model_name='freezingtunnelmanager',
            name='Freezing_tunnel_Manager_id',
            field=models.CharField(default='144046805384434228209547051400942461551', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='live_weighbridge_id',
            field=models.CharField(default='144050704202311555157600029698738496111', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date',
            field=models.FloatField(default=1647182384.1356566, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridgemanager',
            name='Live_Weighbridge_Manager_id',
            field=models.CharField(default='144047245893017807519264071505306329711', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='box_id',
            field=models.CharField(default='144055205946505615657262094865996587631', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='exit_time',
            field=models.FloatField(default=1647182384.1412237, null=True),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time',
            field=models.FloatField(default=1647182384.1411936),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='precold',
            name='pc_id',
            field=models.CharField(default='144052195276330073612433540195883819631', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_format',
            field=models.CharField(default='Sun Mar 13 14:39:44 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_obj',
            field=models.FloatField(default=1647182384.137502),
        ),
        migrations.AlterField(
            model_name='precoldmanager',
            name='Pre_Cold_id',
            field=models.CharField(default='144047760083792525094815053605544010351', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='product_owner_id',
            field=models.CharField(default='144048588018090799157142906139825021551', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='sales_manager_id',
            field=models.CharField(default='144045919613577318734252755579577705071', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slaughteremployee',
            name='Slaughter_Employee_id',
            field=models.CharField(default='144048184746743601551664555001117811311', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightliftingmanager',
            name='Weight_Lifting_Manager_id',
            field=models.CharField(default='144046364875850648899830031296578593391', max_length=250, primary_key=True, serialize=False),
        ),
    ]
