# Generated by Django 4.0.3 on 2022-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseApp', '0022_distributedroot_out_status_alter_automation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributed',
            name='number_of_box',
        ),
        migrations.RemoveField(
            model_name='distributed',
            name='sales_input_idistd',
        ),
        migrations.AddField(
            model_name='distributed',
            name='buyer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributed',
            name='description',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AddField(
            model_name='distributed',
            name='saleor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributed',
            name='sub_product_category',
            field=models.CharField(choices=[('W', 'wing'), ('N', 'neck'), ('E', 'leg'), ('H', 'heart'), ('L', 'liver'), ('K', 'kidney'), ('S', 'sangdan'), ('B', 'body'), ('O', 'other')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='automation',
            name='code',
            field=models.CharField(default=7274, max_length=10),
        ),
        migrations.AlterField(
            model_name='aviculture',
            name='aviculture_id',
            field=models.CharField(default='254936444066046559027441544308050504275', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default='254934758090748255482337553692787354195', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='ceo_id',
            field=models.CharField(default='254931241944895872431035152212271442515', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='cold_house_primary_key',
            field=models.CharField(default='254940433996310777379482755181389425235', max_length=150),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date',
            field=models.FloatField(default=1647185960.071969),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='254930368058263340095391495422499236435', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='bill_of_lading',
            field=models.CharField(default='254939328763443703391973325243282238035', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date',
            field=models.FloatField(default=1647185960.070469),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='sales_input_category',
            field=models.CharField(choices=[('G', 'Gate-bandi'), ('F', 'First-weight-lifting'), ('T', 'Freeze-tunnel'), ('C', 'Cold-House'), ('P', 'Pre-Cold')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='sales_manager',
            field=models.CharField(default='Admin', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='dist_id',
            field=models.CharField(default='254938663246878583571537539474099415635', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time',
            field=models.FloatField(default=1647185960.06977),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time',
            field=models.FloatField(default=1647185960.0698),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time',
            field=models.FloatField(default=1647185960.0698206),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time',
            field=models.FloatField(default=1647185960.0697348),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='254935145516462950234948386122704497235', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weight_lifting_id',
            field=models.CharField(default='254937695871014284403975522302465813075', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time',
            field=models.FloatField(default=1647185960.0683792),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date',
            field=models.FloatField(default=1647185960.0711432),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='freeze_tunnel_id',
            field=models.CharField(default='254939780363970034698697608443799153235', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='input_id',
            field=models.CharField(default='254940034686371705487221283719879731795', max_length=200),
        ),
        migrations.AlterField(
            model_name='freezingtunnelmanager',
            name='Freezing_tunnel_Manager_id',
            field=models.CharField(default='254932638737400998911306926392115866195', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='live_weighbridge_id',
            field=models.CharField(default='254936669074028099538160309972869458515', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date',
            field=models.FloatField(default=1647185960.067264, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridgemanager',
            name='Live_Weighbridge_Manager_id',
            field=models.CharField(default='254933083207392703934240826173677251155', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='box_id',
            field=models.CharField(default='254941203301768790886200788493147187795', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='exit_time',
            field=models.FloatField(default=1647185960.0728688, null=True),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time',
            field=models.FloatField(default=1647185960.072838),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='precold',
            name='pc_id',
            field=models.CharField(default='254938084881292229441873106603261962835', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_format',
            field=models.CharField(default='Sun Mar 13 15:39:20 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_obj',
            field=models.FloatField(default=1647185960.0690033),
        ),
        migrations.AlterField(
            model_name='precoldmanager',
            name='Pre_Cold_id',
            field=models.CharField(default='254933615620644799790589454789023509075', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='product_owner_id',
            field=models.CharField(default='254934449100914449851420938871381043795', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='sales_manager_id',
            field=models.CharField(default='254931749797417588865439126828993096275', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slaughteremployee',
            name='Slaughter_Employee_id',
            field=models.CharField(default='254934053752383503672376347087068867155', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightliftingmanager',
            name='Weight_Lifting_Manager_id',
            field=models.CharField(default='254932199021099044744233282223191501395', max_length=250, primary_key=True, serialize=False),
        ),
    ]
