# Generated by Django 4.0.3 on 2022-03-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WareHouseApp', '0023_remove_distributed_number_of_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentation',
            name='box_num',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='choice_status',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='first_weight_lifting',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='pre_cold_manager',
        ),
        migrations.AddField(
            model_name='segmentation',
            name='buyer',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='description',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WareHouseApp.driver'),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='num_weight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='product_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='saleor',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='segment_manager',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='code',
            field=models.CharField(default=2729, max_length=10),
        ),
        migrations.AlterField(
            model_name='aviculture',
            name='aviculture_id',
            field=models.CharField(default='178269082653269844454745400722381305091', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(default='178267445007150674610887342168927859971', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='ceo_id',
            field=models.CharField(default='178263986697856926972551383975495693571', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='cold_house_primary_key',
            field=models.CharField(default='178273056737901559953919092886930158851', max_length=150),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date',
            field=models.FloatField(default=1647190587.768161),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='coldhouse',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='178263330688671308863836109431586911491', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='bill_of_lading',
            field=models.CharField(default='178271948335907985395836159207064958211', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date',
            field=models.FloatField(default=1647190587.7666543),
        ),
        migrations.AlterField(
            model_name='distributed',
            name='date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='dist_id',
            field=models.CharField(default='178271283611624490718043749373321639171', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time',
            field=models.FloatField(default=1647190587.765956),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='empty_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time',
            field=models.FloatField(default=1647190587.7659793),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='enter_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time',
            field=models.FloatField(default=1647190587.7660031),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='exit_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time',
            field=models.FloatField(default=1647190587.765922),
        ),
        migrations.AlterField(
            model_name='distributedroot',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='178267826886893993364994543050768479491', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weight_lifting_id',
            field=models.CharField(default='178270336042800820116566130587675620611', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time',
            field=models.FloatField(default=1647190587.764597),
        ),
        migrations.AlterField(
            model_name='firstweightlifting',
            name='weighting_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date',
            field=models.FloatField(default=1647190587.7673323),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='entry_date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='exit_date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='freeze_tunnel_id',
            field=models.CharField(default='178272400728715941845203818343021376771', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freezingtunnel',
            name='input_id',
            field=models.CharField(default='178272647920582986349937110200146425091', max_length=200),
        ),
        migrations.AlterField(
            model_name='freezingtunnelmanager',
            name='Freezing_tunnel_Manager_id',
            field=models.CharField(default='178265370813856051170529143188308063491', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='live_weighbridge_id',
            field=models.CharField(default='178269302115280008966960534839123735811', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date',
            field=models.FloatField(default=1647190587.763461, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridge',
            name='weighting_date_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='liveweighbridgemanager',
            name='Live_Weighbridge_Manager_id',
            field=models.CharField(default='178265815283847756193463042969869448451', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='box_id',
            field=models.CharField(default='178273818120543322034203366844292887811', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='exit_time',
            field=models.FloatField(default=1647190587.769047, null=True),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time',
            field=models.FloatField(default=1647190587.7690165),
        ),
        migrations.AlterField(
            model_name='paperbox',
            name='packing_time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='precold',
            name='pc_id',
            field=models.CharField(default='178270809034931030274661564045059126531', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_format',
            field=models.CharField(default='Sun Mar 13 16:56:27 2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='precold',
            name='time_obj',
            field=models.FloatField(default=1647190587.7653248),
        ),
        migrations.AlterField(
            model_name='precoldmanager',
            name='Pre_Cold_id',
            field=models.CharField(default='178266319174961346914650137909393585411', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='product_owner_id',
            field=models.CharField(default='178267132848190368409397223605763536131', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='sales_manager_id',
            field=models.CharField(default='178264489796688892551095102979580327171', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='output_category',
            field=models.CharField(choices=[('D', 'distribute'), ('F', 'freeze-tunnel'), ('P', 'pre-cold'), ('G', 'podr-gosht')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='sub_product_category',
            field=models.CharField(choices=[('sbap', 'sine-ba-post'), ('sbip', 'sine-bi-post'), ('rbap', 'ran-ba-post'), ('rbip', 'ran-bi-post'), ('mrb', 'magz-rub-boshgabi'), ('srb', 'sag-ran-boshgabi'), ('bb1k', 'bal-boshgabi-1-kilo'), ('bkhb1k', 'bikhas-boshgabi-1-kilo'), ('fb1k', 'file-bohgabi-1-kilo'), ('kb1k', 'ketf-boshgabi-1-kilo'), ('eb800g', 'eskelet-boshgabi-800-geram'), ('ef', 'eskelet-falle'), ('bkhbikf', 'bikhas-bi-ketf-falle'), ('bkhbakf', 'bikhas-ba-ketf-falle'), ('sdbapf', 'sine-doroste-ba-post-falle'), ('rf', 'ran-falle'), ('jz', 'joje-zaferani'), ('js', 'joje-sade'), ('fz', 'file-zaferani'), ('fs', 'file-sade'), ('bz', 'bal-zaferani'), ('bs', 'bal-sade'), ('bban', 'bal-ba-nok'), ('bbin', 'bal-bi-nok'), ('kz', 'ketf-zaferani'), ('kbap', 'ketf-ba-post'), ('gb', 'gardan-boshgabi'), ('sdbbvg', 'sine-doroste-ba-bal-v-gardan'), ('O', 'other')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='slaughteremployee',
            name='Slaughter_Employee_id',
            field=models.CharField(default='178266737499659422230352631821451359491', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightliftingmanager',
            name='Weight_Lifting_Manager_id',
            field=models.CharField(default='178264929512990846718168747148504691971', max_length=250, primary_key=True, serialize=False),
        ),
    ]
