# Generated by Django 3.1.3 on 2022-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='sub_task_id',
            field=models.CharField(default='70583901544542268676901907390994018519', max_length=250),
        ),
        migrations.AlterField(
            model_name='subtaskstructure',
            name='sub_task_structure_id',
            field=models.CharField(default='70583901386085943648373232203906117847', max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='70583901465314106162637569797450068183', max_length=250),
        ),
        migrations.AlterField(
            model_name='taskstructure',
            name='task_structure_id',
            field=models.CharField(default='70583901306857781134108894610362167511', max_length=100),
        ),
    ]
